name: Update Vulnerable Packages From S3 to GitHub

on:
  push:
    branches: 
      - "main"
  schedule:
    - cron: "30 12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build Start Slack Notification
      uses: ravsamhq/notify-slack-action@v2
      with:
        status: warnings
        token: ${{ secrets.GITHUB_TOKEN }}
        notification_title: "Build started in <{repo_url}|{repo}>."
        message_format: "Workflow: *{workflow}* \t Repo:<{repo_url}|{repo}> \n Author:${{ github.actor }} \t \tRef:${{ github.ref }}"
        notify_when: "warnings"
        footer: "Linked Repo <{repo_url}|{repo}> | <{workflow_url}|View Workflow>"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.STROBES_INTEL_S3_READ_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.STROBES_INTEL_S3_READ_ACCESS_SECRET }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Download file from S3, Compress json file & commit changes
      run: |
        date=$(date +'%Y-%m-%d')
        rm -rf vulnerable_products.jsonl.tgz
        aws s3 cp s3://strobes-intel/$date.tar.gz .
        mkdir $date
        tar -xvf $date.tar.gz -C $date
        tar -czf vulnerable_products.jsonl.tgz $date/vulnerable_products.jsonl
        rm -rf $date*
        git config --global user.name 'GitHub'
        git config --global user.email 'noreply@github.com'
        git add vulnerable_products.jsonl.tgz
        git commit -m "updated vulnerable packages"
        git push -u origin main
    
    - name: Build Success Slack Notification
      uses: ravsamhq/notify-slack-action@v2
      if: always()
      with:
        status: ${{ job.status }}
        token: ${{ secrets.GITHUB_TOKEN }}
        notification_title: "*Build Succeeded.*"
        message_format: "{emoji} Workflow: *{workflow}* \t Repo:<{repo_url}|{repo}> \n Author:${{ github.actor }} \t \tRef:${{ github.ref }}"
        footer: "Linked Repo <{repo_url}|{repo}> | <{workflow_url}|View Workflow>"
        notify_when: "success"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Build Failure Slack Notification
      uses: ravsamhq/notify-slack-action@v2
      if: always()
      with:
        status: ${{ job.status }}
        token: ${{ secrets.GITHUB_TOKEN }}
        notification_title: "*Build Failed.*"
        message_format: "{emoji} Workflow: *{workflow}* \t Repo:<{repo_url}|{repo}> \n Author:${{ github.actor }} \t \tRef:${{ github.ref }}"
        footer: "Linked Repo <{repo_url}|{repo}> | <{workflow_url}|View Workflow>"
        notify_when: "failure"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
